# Generated by Django 2.1.5 on 2022-01-21 14:27

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicifyapp', '0003_auto_20220121_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 21, 20, 27, 44, 202474))),
            ],
        ),
        migrations.CreateModel(
            name='Blogs_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_subject', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 21, 20, 27, 44, 203471))),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.blog_post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 21, 20, 27, 44, 199452)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 21, 20, 27, 44, 199452)),
        ),
    ]
