# Generated by Django 2.1.5 on 2022-01-21 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0005_auto_20220121_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='Blog_video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Blog_video'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 21, 22, 32, 55, 470667)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 21, 22, 32, 55, 471664)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 21, 22, 32, 55, 469669)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 21, 22, 32, 55, 468672)),
        ),
    ]
