# Generated by Django 2.1.5 on 2022-01-28 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0007_auto_20220127_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='Brands',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.Brands'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 29, 0, 21, 23, 744193)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 29, 0, 21, 23, 745191)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 29, 0, 21, 23, 743196)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 29, 0, 21, 23, 742199)),
        ),
    ]
