# Generated by Django 2.1.5 on 2022-01-29 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0010_auto_20220129_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Company_Name', models.CharField(max_length=255)),
                ('Email_Adress', models.CharField(max_length=255)),
                ('Phone_Number', models.CharField(max_length=255)),
                ('Project_Name', models.CharField(max_length=255)),
                ('Details', models.TextField(blank=True, null=True)),
                ('Attach_File', models.FileField(blank=True, null=True, upload_to='custom_project/attach/')),
            ],
            options={
                'verbose_name_plural': 'Custom Project',
            },
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 29, 16, 33, 1, 938106)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 29, 16, 33, 1, 939104)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 29, 16, 33, 1, 937109)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 29, 16, 33, 1, 936112)),
        ),
    ]
