# Generated by Django 2.1.5 on 2022-01-30 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0013_auto_20220129_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'catalog'},
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='catalog_File',
        ),
        migrations.AddField(
            model_name='catalog',
            name='catalog_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 15, 31, 230286)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 15, 31, 231283)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 15, 31, 229288)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 15, 31, 228291)),
        ),
    ]
