# Generated by Django 2.1.5 on 2022-01-30 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0014_auto_20220130_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 17, 57, 375713)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 17, 57, 376710)),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalog_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 17, 57, 374716)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 30, 16, 17, 57, 372720)),
        ),
    ]
