# Generated by Django 2.1.5 on 2022-01-31 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0016_auto_20220131_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter_table',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 8, 39, 359972)),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 8, 39, 356980)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 8, 39, 357978)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 8, 39, 354985)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 8, 39, 354985)),
        ),
    ]
