# Generated by Django 2.1.5 on 2022-01-31 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0017_auto_20220131_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='price',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 11, 15, 416538)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 11, 15, 417495)),
        ),
        migrations.AlterField(
            model_name='newsletter_table',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 11, 15, 418491)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 11, 15, 415499)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 22, 11, 15, 414501)),
        ),
    ]
