# Generated by Django 2.1.5 on 2022-01-31 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0018_auto_20220131_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_bill',
        ),
        migrations.AddField(
            model_name='order',
            name='Discount_Coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.Discount_Coupon'),
        ),
        migrations.AlterField(
            model_name='bennar',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 0, 11, 2, 151459)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 0, 11, 2, 152456)),
        ),
        migrations.AlterField(
            model_name='brands',
            name='Brand_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact_table',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact_table',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='discount_coupon',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='discount_coupon',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfirmed',
            name='activation_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job_post_status',
            name='job_post_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsletter_table',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 0, 11, 2, 153453)),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 1, 0, 11, 2, 150462)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='job_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='job_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 1, 0, 11, 2, 149463)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='salary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_status',
            field=models.CharField(choices=[('New', 'New'), ('In stock', 'In stock'), ('Out stock', 'Out stock')], default='New', max_length=255),
        ),
    ]
